package main

type PowerHint int32
const (
	//Android Open Source Project
	HINT_VSYNC PowerHint = iota + 0x00000001
	HINT_INTERACTION
	HINT_VIDEO_ENCODE
	HINT_VIDEO_DECODE
	HINT_LOW_POWER
	HINT_SUSTAINED_PERFORMANCE
	HINT_VR_MODE
	HINT_LAUNCH
	HINT_AUDIO_STREAMING
	HINT_AUDIO_LOW_LATENCY
	HINT_CAMERA_LAUNCH
	HINT_CAMERA_STREAMING
	HINT_CAMERA_SHOT
	HINT_EXPENSIVE_RENDERING

	//LineageOS
	HINT_LINEAGE_CPU_BOOST   PowerHint = 0x00000110
	HINT_LINEAGE_SET_PROFILE PowerHint = 0x00000111
)

type PowerFeature int32
const (
	//Android Open Source Project
	FEATURE_DOUBLE_TAP_TO_WAKE PowerFeature = 0x00000001

	//LineageOS
	FEATURE_SUPPORTED_PROFILES PowerFeature = 0x00001000
)